project_id = "lewvnkdganfaavpwakah"

[functions.manage-employee]
verify_jwt = true

[functions.create-employee]
verify_jwt = true

[functions.complete-invitation]
verify_jwt = false

[functions.ai-extract-expense]
verify_jwt = false

[functions.upload-to-dropbox]
verify_jwt = true
